# Generated by Django 6.0.6 on 2026-06-19 21:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=255, unique=True)),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Campus",
                "verbose_name_plural": "Campi",
                "ordering": ("nome",),
            },
        ),
        migrations.CreateModel(
            name="DispositivoEsp32",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("nome", models.CharField(max_length=255)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "interscity_uuid",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispositivo ESP32",
                "verbose_name_plural": "Dispositivos ESP32",
                "ordering": ("codigo",),
            },
        ),
        migrations.CreateModel(
            name="EventoSincronizacaoBorda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entidade",
                    models.CharField(
                        choices=[
                            ("salas", "Salas"),
                            ("dispositivos", "Dispositivos"),
                            ("aulas", "Aulas"),
                            ("alunos", "Alunos"),
                            ("matriculas_turma", "Matriculas em turma"),
                            ("embeddings_faciais", "Embeddings faciais"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("UPSERT", "Criar ou atualizar"),
                            ("DELETE", "Remover"),
                        ],
                        max_length=10,
                    ),
                ),
                ("identificador", models.UUIDField(db_index=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Evento de sincronizacao de borda",
                "verbose_name_plural": "Eventos de sincronizacao de borda",
                "ordering": ("id",),
                "indexes": [
                    models.Index(
                        fields=["entidade", "identificador", "id"],
                        name="api_eventos_entidad_caf925_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HorarioPadraoUFMA",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("codigo", models.CharField(max_length=20, unique=True)),
                (
                    "dia_semana",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (2, "Segunda-feira"),
                            (3, "Terca-feira"),
                            (4, "Quarta-feira"),
                            (5, "Quinta-feira"),
                            (6, "Sexta-feira"),
                            (7, "Sabado"),
                        ]
                    ),
                ),
                ("horario_inicio", models.TimeField()),
                ("horario_fim", models.TimeField()),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Horario padrao UFMA",
                "verbose_name_plural": "Horarios padrao UFMA",
                "ordering": ("dia_semana", "horario_inicio", "codigo"),
            },
        ),
        migrations.CreateModel(
            name="NoBorda",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("nome", models.CharField(max_length=255)),
                ("ativo", models.BooleanField(default=True)),
                ("ultimo_sync_em", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "No de borda",
                "verbose_name_plural": "Nos de borda",
                "ordering": ("codigo",),
            },
        ),
        migrations.CreateModel(
            name="PeriodoLetivo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                ("ativo", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Periodo letivo",
                "verbose_name_plural": "Periodos letivos",
                "ordering": ("-data_inicio",),
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "papel",
                    models.CharField(
                        choices=[
                            ("ALUNO", "Aluno"),
                            ("PROFESSOR", "Professor"),
                            ("ADMINISTRADOR", "Administrador"),
                        ],
                        max_length=20,
                    ),
                ),
                ("matricula", models.CharField(blank=True, max_length=50)),
                ("nome_completo", models.CharField(blank=True, max_length=255)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "ordering": ("username",),
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Aula",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("data", models.DateField()),
                ("inicio", models.DateTimeField()),
                ("fim", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANEJADA", "Planejada"),
                            ("ABERTA", "Aberta"),
                            ("FECHADA", "Fechada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PLANEJADA",
                        max_length=20,
                    ),
                ),
                ("fechada_em", models.DateTimeField(blank=True, null=True)),
                (
                    "fechada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aulas_fechadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "horario_padrao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aulas",
                        to="api.horariopadraoufma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aula",
                "verbose_name_plural": "Aulas",
                "ordering": ("data", "inicio"),
            },
        ),
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=255)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cursos",
                        to="api.campus",
                    ),
                ),
            ],
            options={
                "verbose_name": "Curso",
                "verbose_name_plural": "Cursos",
                "ordering": ("nome",),
            },
        ),
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("codigo", models.CharField(max_length=30)),
                ("nome", models.CharField(max_length=255)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disciplinas",
                        to="api.curso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disciplina",
                "verbose_name_plural": "Disciplinas",
                "ordering": ("curso__nome", "codigo"),
            },
        ),
        migrations.CreateModel(
            name="EmbeddingFacial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("versao_modelo", models.CharField(max_length=50)),
                ("vetor", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ATIVO", "Ativo"),
                            ("INATIVO", "Inativo"),
                            ("REVOGADO", "Revogado"),
                        ],
                        default="ATIVO",
                        max_length=20,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings_faciais",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Embedding facial",
                "verbose_name_plural": "Embeddings faciais",
                "ordering": ("aluno__username", "-criado_em"),
            },
        ),
        migrations.CreateModel(
            name="EventoReconhecimento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "id_evento_origem",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "confianca",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                ("reconhecido", models.BooleanField(default=False)),
                (
                    "ocorrido_em",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "aluno_candidato",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos_reconhecimento",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "aula",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos_reconhecimento",
                        to="api.aula",
                    ),
                ),
                (
                    "dispositivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos_reconhecimento",
                        to="api.dispositivoesp32",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de reconhecimento",
                "verbose_name_plural": "Eventos de reconhecimento",
                "ordering": ("-ocorrido_em",),
            },
        ),
        migrations.AddField(
            model_name="dispositivoesp32",
            name="no",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dispositivos",
                to="api.noborda",
            ),
        ),
        migrations.CreateModel(
            name="Predio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=255)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predios",
                        to="api.campus",
                    ),
                ),
            ],
            options={
                "verbose_name": "Predio",
                "verbose_name_plural": "Predios",
                "ordering": ("campus__nome", "nome"),
            },
        ),
        migrations.CreateModel(
            name="RegistroPresenca",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENTE", "Presente"),
                            ("AUSENTE", "Ausente"),
                            ("ATRASO", "Atraso"),
                            ("JUSTIFICADA", "Justificada"),
                        ],
                        default="PRESENTE",
                        max_length=20,
                    ),
                ),
                (
                    "registrado_em",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presencas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "aula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presencas",
                        to="api.aula",
                    ),
                ),
                (
                    "registrado_por_dispositivo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="presencas_registradas",
                        to="api.dispositivoesp32",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de presenca",
                "verbose_name_plural": "Registros de presenca",
                "ordering": ("aula__data", "aluno__username"),
            },
        ),
        migrations.CreateModel(
            name="Sala",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=255)),
                ("codigo", models.CharField(max_length=20)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "predio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salas",
                        to="api.predio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sala",
                "verbose_name_plural": "Salas",
                "ordering": ("predio__campus__nome", "predio__nome", "nome"),
            },
        ),
        migrations.AddField(
            model_name="dispositivoesp32",
            name="sala",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dispositivos",
                to="api.sala",
            ),
        ),
        migrations.AddField(
            model_name="aula",
            name="sala",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="aulas",
                to="api.sala",
            ),
        ),
        migrations.CreateModel(
            name="TokenNoBorda",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=100)),
                ("prefixo_token", models.CharField(db_index=True, max_length=12)),
                ("hash_token", models.CharField(max_length=64, unique=True)),
                ("ativo", models.BooleanField(default=True)),
                ("expira_em", models.DateTimeField(blank=True, null=True)),
                ("ultimo_uso_em", models.DateTimeField(blank=True, null=True)),
                (
                    "no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="api.noborda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token do no de borda",
                "verbose_name_plural": "Tokens dos nos de borda",
                "ordering": ("no__codigo", "-criado_em"),
            },
        ),
        migrations.CreateModel(
            name="Turma",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("codigo", models.CharField(max_length=50)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="turmas",
                        to="api.disciplina",
                    ),
                ),
                (
                    "periodo_letivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="turmas",
                        to="api.periodoletivo",
                    ),
                ),
                (
                    "professores",
                    models.ManyToManyField(
                        blank=True,
                        related_name="turmas_ministradas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Turma",
                "verbose_name_plural": "Turmas",
                "ordering": (
                    "periodo_letivo__data_inicio",
                    "disciplina__codigo",
                    "codigo",
                ),
            },
        ),
        migrations.CreateModel(
            name="MatriculaTurma",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matriculas_turma",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matriculas",
                        to="api.turma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matricula em turma",
                "verbose_name_plural": "Matriculas em turma",
                "ordering": ("turma__disciplina__codigo", "aluno__username"),
            },
        ),
        migrations.AddField(
            model_name="aula",
            name="turma",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aulas",
                to="api.turma",
            ),
        ),
        migrations.AddConstraint(
            model_name="usuario",
            constraint=models.UniqueConstraint(
                condition=models.Q(("email", ""), _negated=True),
                fields=("email",),
                name="uq_usuario_email_preenchido",
            ),
        ),
        migrations.AddConstraint(
            model_name="curso",
            constraint=models.UniqueConstraint(
                fields=("campus", "nome"), name="uq_curso_campus_nome"
            ),
        ),
        migrations.AddConstraint(
            model_name="disciplina",
            constraint=models.UniqueConstraint(
                fields=("curso", "codigo"), name="uq_disc_curso_codigo"
            ),
        ),
        migrations.AddConstraint(
            model_name="embeddingfacial",
            constraint=models.UniqueConstraint(
                fields=("aluno",),
                name="uq_embedding_aluno",
            ),
        ),
        migrations.AddConstraint(
            model_name="predio",
            constraint=models.UniqueConstraint(
                fields=("campus", "nome"), name="uq_predio_campus_nome"
            ),
        ),
        migrations.AddConstraint(
            model_name="registropresenca",
            constraint=models.UniqueConstraint(
                fields=("aula", "aluno"), name="uq_presenca_aula_aluno"
            ),
        ),
        migrations.AddConstraint(
            model_name="sala",
            constraint=models.UniqueConstraint(
                fields=("predio", "codigo"), name="uq_sala_predio_codigo"
            ),
        ),
        migrations.AddConstraint(
            model_name="dispositivoesp32",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ativo", True)),
                fields=("sala",),
                name="uq_disp_sala_ativo",
            ),
        ),
        migrations.AddConstraint(
            model_name="turma",
            constraint=models.UniqueConstraint(
                fields=("periodo_letivo", "disciplina", "codigo"),
                name="uq_turma_periodo_disc_cod",
            ),
        ),
        migrations.AddConstraint(
            model_name="matriculaturma",
            constraint=models.UniqueConstraint(
                fields=("turma", "aluno"), name="uq_matricula_turma_aluno"
            ),
        ),
        migrations.AddConstraint(
            model_name="aula",
            constraint=models.UniqueConstraint(
                fields=("turma", "horario_padrao", "data"),
                name="uq_aula_turma_slot_data",
            ),
        ),
    ]
