# Generated by Django 6.0.4 on 2026-06-07 02:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aula",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("data", models.DateField()),
                ("inicio", models.DateTimeField()),
                ("fim", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANEJADA", "Planejada"),
                            ("ABERTA", "Aberta"),
                            ("FECHADA", "Fechada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PLANEJADA",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Aula",
                "verbose_name_plural": "Aulas",
                "ordering": ("data", "inicio"),
            },
        ),
        migrations.CreateModel(
            name="Campus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=255, unique=True)),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Campus",
                "verbose_name_plural": "Campi",
                "ordering": ("nome",),
            },
        ),
        migrations.CreateModel(
            name="DispositivoEsp32",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("nome", models.CharField(max_length=255)),
                ("ativo", models.BooleanField(default=True)),
                ("ultimo_sync_em", models.DateTimeField(blank=True, null=True)),
                ("versao_firmware", models.CharField(blank=True, max_length=50)),
                (
                    "interscity_uuid",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
            ],
            options={
                "verbose_name": "Dispositivo ESP32",
                "verbose_name_plural": "Dispositivos ESP32",
                "ordering": ("codigo",),
            },
        ),
        migrations.CreateModel(
            name="HorarioAula",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("dia_semana", models.PositiveSmallIntegerField()),
                ("horario_inicio", models.TimeField()),
                ("horario_fim", models.TimeField()),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Horário de aula",
                "verbose_name_plural": "Horários de aula",
                "ordering": (
                    "turma__disciplina__codigo",
                    "dia_semana",
                    "horario_inicio",
                ),
            },
        ),
        migrations.CreateModel(
            name="NoBorda",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("nome", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True)),
                ("ativo", models.BooleanField(default=True)),
                ("ultimo_sync_em", models.DateTimeField(blank=True, null=True)),
                ("versao_software", models.CharField(blank=True, max_length=50)),
                (
                    "interscity_uuid",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
            ],
            options={
                "verbose_name": "Nó de borda",
                "verbose_name_plural": "Nós de borda",
                "ordering": ("codigo",),
            },
        ),
        migrations.CreateModel(
            name="PeriodoLetivo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                ("ativo", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Período letivo",
                "verbose_name_plural": "Períodos letivos",
                "ordering": ("-data_inicio",),
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "papel",
                    models.CharField(
                        choices=[
                            ("ALUNO", "Aluno"),
                            ("PROFESSOR", "Professor"),
                            ("ADMINISTRADOR", "Administrador"),
                        ],
                        max_length=20,
                    ),
                ),
                ("matricula", models.CharField(blank=True, max_length=50)),
                ("nome_completo", models.CharField(blank=True, max_length=255)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
                "ordering": ("username",),
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("nome", models.CharField(max_length=255)),
                ("turno", models.CharField(blank=True, max_length=50)),
                (
                    "duracao_minima_periodos",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "duracao_maxima_periodos",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cursos",
                        to="api.campus",
                    ),
                ),
            ],
            options={
                "verbose_name": "Curso",
                "verbose_name_plural": "Cursos",
                "ordering": ("codigo",),
            },
        ),
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("codigo", models.CharField(max_length=30)),
                ("nome", models.CharField(max_length=255)),
                ("carga_horaria", models.PositiveSmallIntegerField(default=0)),
                ("periodo_sugerido", models.PositiveSmallIntegerField(default=0)),
                ("obrigatoria", models.BooleanField(default=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disciplinas",
                        to="api.curso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disciplina",
                "verbose_name_plural": "Disciplinas",
                "ordering": ("curso__codigo", "codigo"),
            },
        ),
        migrations.CreateModel(
            name="EventoReconhecimento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "id_evento_origem",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "confianca",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                ("reconhecido", models.BooleanField(default=False)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "ocorrido_em",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "aluno_candidato",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos_reconhecimento",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "aula",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos_reconhecimento",
                        to="api.aula",
                    ),
                ),
                (
                    "dispositivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos_reconhecimento",
                        to="api.dispositivoesp32",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de reconhecimento",
                "verbose_name_plural": "Eventos de reconhecimento",
                "ordering": ("-ocorrido_em",),
            },
        ),
        migrations.AddField(
            model_name="aula",
            name="horario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aulas",
                to="api.horarioaula",
            ),
        ),
        migrations.AddField(
            model_name="dispositivoesp32",
            name="no",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dispositivos",
                to="api.noborda",
            ),
        ),
        migrations.CreateModel(
            name="ComandoBorda",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("tipo", models.CharField(max_length=100)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("ENTREGUE", "Entregue"),
                            ("FALHOU", "Falhou"),
                            ("REJEITADO", "Rejeitado"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                    ),
                ),
                ("origem", models.CharField(default="backend", max_length=50)),
                (
                    "id_origem",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("capacidade", models.CharField(blank=True, max_length=100)),
                ("entregue_em", models.DateTimeField(blank=True, null=True)),
                ("ultimo_erro", models.TextField(blank=True)),
                (
                    "dispositivo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comandos",
                        to="api.dispositivoesp32",
                    ),
                ),
                (
                    "no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comandos",
                        to="api.noborda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comando de borda",
                "verbose_name_plural": "Comandos de borda",
                "ordering": ("criado_em",),
            },
        ),
        migrations.CreateModel(
            name="PerfilBiometrico",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("ATIVO", "Ativo"),
                            ("INATIVO", "Inativo"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                (
                    "aluno",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_biometrico",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil biométrico",
                "verbose_name_plural": "Perfis biométricos",
                "ordering": ("aluno__username",),
            },
        ),
        migrations.CreateModel(
            name="EmbeddingFacial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("versao_modelo", models.CharField(max_length=50)),
                ("vetor", models.JSONField()),
                (
                    "pontuacao_qualidade",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                ("metadados_origem", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ATIVO", "Ativo"),
                            ("INATIVO", "Inativo"),
                            ("REVOGADO", "Revogado"),
                        ],
                        default="ATIVO",
                        max_length=20,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="api.perfilbiometrico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Embedding facial",
                "verbose_name_plural": "Embeddings faciais",
                "ordering": ("perfil__aluno__username", "-criado_em"),
            },
        ),
        migrations.CreateModel(
            name="Predio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=255)),
                ("codigo", models.CharField(max_length=20)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predios",
                        to="api.campus",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prédio",
                "verbose_name_plural": "Prédios",
                "ordering": ("campus__nome", "nome"),
            },
        ),
        migrations.CreateModel(
            name="RegistroPresenca",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENTE", "Presente"),
                            ("AUSENTE", "Ausente"),
                            ("ATRASO", "Atraso"),
                            ("JUSTIFICADA", "Justificada"),
                        ],
                        default="PRESENTE",
                        max_length=20,
                    ),
                ),
                (
                    "registrado_em",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presencas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "aula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presencas",
                        to="api.aula",
                    ),
                ),
                (
                    "registrado_por_dispositivo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="presencas_registradas",
                        to="api.dispositivoesp32",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de presença",
                "verbose_name_plural": "Registros de presença",
                "ordering": ("aula__data", "aluno__username"),
            },
        ),
        migrations.CreateModel(
            name="Sala",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=255)),
                ("codigo", models.CharField(max_length=20)),
                ("andar", models.CharField(blank=True, max_length=20)),
                ("capacidade", models.PositiveIntegerField(default=0)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "predio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salas",
                        to="api.predio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sala",
                "verbose_name_plural": "Salas",
                "ordering": ("predio__campus__nome", "predio__nome", "nome"),
            },
        ),
        migrations.AddField(
            model_name="horarioaula",
            name="sala",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="horarios_aula",
                to="api.sala",
            ),
        ),
        migrations.AddField(
            model_name="dispositivoesp32",
            name="sala",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dispositivos",
                to="api.sala",
            ),
        ),
        migrations.CreateModel(
            name="TokenNoBorda",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=100)),
                ("prefixo_token", models.CharField(db_index=True, max_length=12)),
                ("hash_token", models.CharField(max_length=64, unique=True)),
                ("ativo", models.BooleanField(default=True)),
                ("expira_em", models.DateTimeField(blank=True, null=True)),
                ("ultimo_uso_em", models.DateTimeField(blank=True, null=True)),
                (
                    "no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="api.noborda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token do nó de borda",
                "verbose_name_plural": "Tokens dos nós de borda",
                "ordering": ("no__codigo", "-criado_em"),
            },
        ),
        migrations.CreateModel(
            name="Turma",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("codigo", models.CharField(max_length=50)),
                ("nome", models.CharField(blank=True, max_length=255)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="turmas",
                        to="api.disciplina",
                    ),
                ),
                (
                    "periodo_letivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="turmas",
                        to="api.periodoletivo",
                    ),
                ),
                (
                    "professores",
                    models.ManyToManyField(
                        blank=True,
                        related_name="turmas_ministradas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Turma",
                "verbose_name_plural": "Turmas",
                "ordering": (
                    "periodo_letivo__data_inicio",
                    "disciplina__codigo",
                    "codigo",
                ),
            },
        ),
        migrations.CreateModel(
            name="MatriculaTurma",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("matriculado_em", models.DateTimeField(auto_now_add=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matriculas_turma",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matriculas",
                        to="api.turma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matrícula em turma",
                "verbose_name_plural": "Matrículas em turma",
                "ordering": ("turma__disciplina__codigo", "aluno__username"),
            },
        ),
        migrations.AddField(
            model_name="horarioaula",
            name="turma",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="horarios",
                to="api.turma",
            ),
        ),
        migrations.AddConstraint(
            model_name="disciplina",
            constraint=models.UniqueConstraint(
                fields=("curso", "codigo"), name="disciplina_codigo_unico_por_curso"
            ),
        ),
        migrations.AddConstraint(
            model_name="aula",
            constraint=models.UniqueConstraint(
                fields=("horario", "data"), name="aula_unica_por_horario_data"
            ),
        ),
        migrations.AddConstraint(
            model_name="comandoborda",
            constraint=models.UniqueConstraint(
                condition=models.Q(("id_origem", ""), _negated=True),
                fields=("origem", "id_origem"),
                name="comando_borda_origem_id_unico",
            ),
        ),
        migrations.AddConstraint(
            model_name="embeddingfacial",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ativo", True)),
                fields=("perfil",),
                name="embedding_ativo_unico_por_perfil",
            ),
        ),
        migrations.AddConstraint(
            model_name="predio",
            constraint=models.UniqueConstraint(
                fields=("campus", "codigo"), name="predio_codigo_unico_por_campus"
            ),
        ),
        migrations.AddConstraint(
            model_name="registropresenca",
            constraint=models.UniqueConstraint(
                fields=("aula", "aluno"), name="presenca_unica_por_aula_aluno"
            ),
        ),
        migrations.AddConstraint(
            model_name="sala",
            constraint=models.UniqueConstraint(
                fields=("predio", "codigo"), name="sala_codigo_unico_por_predio"
            ),
        ),
        migrations.AddConstraint(
            model_name="dispositivoesp32",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ativo", True)),
                fields=("sala",),
                name="dispositivo_ativo_unico_por_sala",
            ),
        ),
        migrations.AddConstraint(
            model_name="turma",
            constraint=models.UniqueConstraint(
                fields=("periodo_letivo", "disciplina", "codigo"),
                name="turma_codigo_unico_por_periodo_disciplina",
            ),
        ),
        migrations.AddConstraint(
            model_name="matriculaturma",
            constraint=models.UniqueConstraint(
                fields=("turma", "aluno"), name="matricula_unica_por_turma_aluno"
            ),
        ),
        migrations.AddConstraint(
            model_name="horarioaula",
            constraint=models.UniqueConstraint(
                fields=("turma", "dia_semana", "horario_inicio"),
                name="horario_unico_por_turma_dia_inicio",
            ),
        ),
    ]
